# **Data Cleaning and Manipulation**

- Remove unnecessary rows to maintain dataset relevance.
- Since each row represents a school, dropping rows is not recommended; instead, null values are replaced with 'Not Applicable'.
- Identify and remove duplicate records to ensure data integrity.
- Detect and handle invalid entries (e.g., "n/a," empty strings).
- Drop columns with excessive invalid entries if they do not significantly impact dashboarding (e.g., address street).
- Standardize data formatting by:
    - Converting text to uppercase for consistency.
    - Resolving inconsistent abbreviations.
    - Removing unnecessary punctuation marks.
- Reshape the dataset from wide to long format for improved analysis.
- Export data with special character considerations to prevent encoding issues.

In [ ]:
# import dataset

import pandas as pd

df = pd.read_csv(r"C:\...\Big Data Analytics\SY 2023-2024 School Level Data on Official Enrollment.csv")
df

C:\Users\kncba\AppData\Local\Temp\ipykernel_4344\3052219247.py:5: DtypeWarning: Columns (3,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(r"C:\Users\kncba\OneDrive\Documents\BSCPE 3-2 Second Semester\Big Data Analytics\SY 2023-2024 School Level Data on Official Enrollment.csv")

,SCHOOL LEVEL DATA ON OFFICIAL ENROLLMENT IN ALL GRADE LEVELS,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36,Unnamed: 37,Unnamed: 38,Unnamed: 39,Unnamed: 40,Unnamed: 41,Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46,Unnamed: 47,Unnamed: 48,Unnamed: 49,Unnamed: 50,Unnamed: 51,Unnamed: 52,Unnamed: 53,Unnamed: 54,Unnamed: 55,Unnamed: 56,Unnamed: 57,Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64,Unnamed: 65,Unnamed: 66,Unnamed: 67,Unnamed: 68,Unnamed: 69,Unnamed: 70,Unnamed: 71
0,SY 2023-2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"Based on LIS, as of January 31, 2024",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kindergarten,NaN,Grade 1,NaN,Grade 2,NaN,Grade 3,NaN,Grade 4,NaN,Grade 5,NaN,Grade 6,NaN,SNEd (Non-Graded ES),NaN,Grade 7,NaN,Grade 8,NaN,Grade 9,NaN,Grade 10,NaN,SNEd (Non-Graded JHS),NaN,Grade 11 ABM,NaN,Grade 11 HUMSS,NaN,Grade 11 STEM,NaN,Grade 11 GAS,NaN,Grade 11 PBM,NaN,Grade 11 TVL,NaN,Grade 11 SPORTs,NaN,Grade 11 ARTs & DESIGN,NaN,Grade 12 ABM,NaN,Grade 12 HUMSS,NaN,Grade 12 STEM,NaN,Grade 12 GAS,NaN,Grade 12 PBM,NaN,Grade 12 TVL,NaN,Grade 12 SPORTs,NaN,Grade 12 ARTs & DESIGN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Male,Female,Male,Female,Male,Female,Male,Female,Male,Female,Male,Female,Male,Female,Male,Female,Male,Female,Male,Female,Male,Female,Male,Female,Male,Female,Male,Female,Male,Female,Male,Female,Male,Female,Male,Female,Male,Female,Male,Female,Male,Female,Male,Female,Male,Female,Male,Female,Male,Female,Male,Female,Male,Female,Male,Female,Male,Female
3,Region,Division,District,BEIS School ID,School Name,Street Address,Province,Municipality,Legislative District,Barangay,Sector,School Subclassification,School Type,Modified COC,K Male,K Female,G1 Male,G1 Female,G2 Male,G2 Female,G3 Male,G3 Female,G4 Male,G4 Female,G5 Male,G5 Female,G6 Male,G6 Female,Elem NG Male,Elem NG Female,G7 Male,G7 Female,G8 Male,G8 Female,G9 Male,G9 Female,G10 Male,G10 Female,JHS NG Male,JHS NG Female,G11 ACAD - ABM Male,G11 ACAD - ABM Female,G11 ACAD - HUMSS Male,G11 ACAD - HUMSS Female,G11 ACAD STEM Male,G11 ACAD STEM Female,G11 ACAD GAS Male,G11 ACAD GAS Female,G11 ACAD PBM Male,G11 ACAD PBM Female,G11 TVL Male,G11 TVL Female,G11 SPORTS Male,G11 SPORTS Female,G11 ARTS Male,G11 ARTS Female,G12 ACAD - ABM Male,G12 ACAD - ABM Female,G12 ACAD - HUMSS Male,G12 ACAD - HUMSS Female,G12 ACAD STEM Male,G12 ACAD STEM Female,G12 ACAD GAS Male,G12 ACAD GAS Female,G12 ACAD PBM Male,G12 ACAD PBM Female,G12 TVL Male,G12 TVL Female,G12 SPORTS Male,G12 SPORTS Female,G12 ARTS Male,G12 ARTS Female
4,Region I,Ilocos Norte,Bacarra I,100001,Apaleng-Libtong ES,"Brgy. 21, Libtong, Bacarra, Ilocos Norte",ILOCOS NORTE,BACARRA,1st District,LIBTONG,Public,DepED Managed,School with no Annexes,Purely ES,4,5,3,2,5,7,5,1,2,2,2,9,2,9,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60166,PSO,Italy,Lazio,700034,International Philippine School in Italy,"Via Onofrio Panvinio, 11, 00162 Rome, Italy",NCR SECOND DISTRICT,CITY OF PASIG,Lone District,NaN,PSO,SCHOOL ABROAD,School with no Annexes,ES and JHS,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
60167,PSO,Sultanate of Oman,Muscat,700026,Philippine School,4277 Way 2740 AlKhuwair,NCR SECOND DISTRICT,CITY OF PASIG,Lone District,NaN,PSO,SCHOOL ABROAD,School with no Annexes,All Offering,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,12,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
60168,PSO,State of Kuwait,Jleeb Al-Shuyoukh,700027,The New Kuwait-Philippines International School,Block 1 Jleeb Al-Shuyoukh,NCR SECOND DISTRICT,CITY OF PASIG,Lone District,NaN,PSO,SCHOOL ABROAD,School with no Annexes,All Offering,24,27,19,10,15,13,14,18,23,13,14,17,19,26,0,0,11,23,20,11,24,17,17,17,0,0,2,7,0,0,5,4,0,0,0,0,0,0,0,0,0,0,4,3,0,0,5,1,0,0,0,0,0,0,0,0,0,0
60169,PSO,State of Kuwait,Fahaheel,700030,Philippine International English School,Block 11 Street 54 Fahaheel,NCR SECOND DISTRICT,CITY OF PASIG,Lone District,NaN,PSO,SCHOOL ABROAD,School with no Annexes,All Offering,0,0,18,25,27,19,24,21,13,0,0,0,22,26,0,0,16,23,21,20,31,21,26,30,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,8,6,1,0,0,0,0,0,0,0,0,0
60170,PSO,Greece,Athens,700031,Philippine School in Greece,"Thimaton Polemou 15 Kareas,Vyronas",NCR SECOND DISTRICT,CITY OF PASIG,Lone District,NaN,PSO,SCHOOL ABROAD,School with no Annexes,ES and JHS,1,1,1,3,2,2,3,4,4,3,4,0,6,3,0,0,7,7,8,2,9,10,5,13,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [39]:
# skip the first 4 rows to fix header alignment
df = pd.read_csv(r'C:\Users\kncba\OneDrive\Documents\BSCPE 3-2 Second Semester\Big Data Analytics\SY 2023-2024 School Level Data on Official Enrollment.csv', skiprows=4)

# show all columns
pd.set_option('display.max_columns', None)
df.head()

,Region,Division,District,BEIS School ID,School Name,Street Address,Province,Municipality,Legislative District,Barangay,Sector,School Subclassification,School Type,Modified COC,K Male,K Female,G1 Male,G1 Female,G2 Male,G2 Female,G3 Male,G3 Female,G4 Male,G4 Female,G5 Male,G5 Female,G6 Male,G6 Female,Elem NG Male,Elem NG Female,G7 Male,G7 Female,G8 Male,G8 Female,G9 Male,G9 Female,G10 Male,G10 Female,JHS NG Male,JHS NG Female,G11 ACAD - ABM Male,G11 ACAD - ABM Female,G11 ACAD - HUMSS Male,G11 ACAD - HUMSS Female,G11 ACAD STEM Male,G11 ACAD STEM Female,G11 ACAD GAS Male,G11 ACAD GAS Female,G11 ACAD PBM Male,G11 ACAD PBM Female,G11 TVL Male,G11 TVL Female,G11 SPORTS Male,G11 SPORTS Female,G11 ARTS Male,G11 ARTS Female,G12 ACAD - ABM Male,G12 ACAD - ABM Female,G12 ACAD - HUMSS Male,G12 ACAD - HUMSS Female,G12 ACAD STEM Male,G12 ACAD STEM Female,G12 ACAD GAS Male,G12 ACAD GAS Female,G12 ACAD PBM Male,G12 ACAD PBM Female,G12 TVL Male,G12 TVL Female,G12 SPORTS Male,G12 SPORTS Female,G12 ARTS Male,G12 ARTS Female
0,Region I,Ilocos Norte,Bacarra I,100001,Apaleng-Libtong ES,"Brgy. 21, Libtong, Bacarra, Ilocos Norte",ILOCOS NORTE,BACARRA,1st District,LIBTONG,Public,DepED Managed,School with no Annexes,Purely ES,4,5,3,2,5,7,5,1,2,2,2,9,2,9,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,Region I,Ilocos Norte,Bacarra I,100002,Bacarra CES,Santa Rita,ILOCOS NORTE,BACARRA,1st District,SANTA RITA (POB.),Public,DepED Managed,School with no Annexes,Purely ES,26,25,33,25,18,29,23,32,30,23,34,35,27,42,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,Region I,Ilocos Norte,Bacarra I,100003,Buyon ES,NONE,ILOCOS NORTE,BACARRA,1st District,BUYON,Public,DepED Managed,School with no Annexes,Purely ES,8,10,11,10,11,4,13,4,8,7,12,14,9,7,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,Region I,Ilocos Norte,Bacarra I,100004,Ganagan Elementary School,"#37 Ganagan,Bacarra, Ilocos Norte",ILOCOS NORTE,BACARRA,1st District,GANAGAN,Public,DepED Managed,School with no Annexes,Purely ES,9,8,5,4,6,5,6,8,7,5,1,13,7,7,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,Region I,Ilocos Norte,Bacarra I,100005,Macupit ES,Macupit,ILOCOS NORTE,BACARRA,1st District,MACUPIT,Public,DepED Managed,School with no Annexes,Purely ES,5,3,5,2,3,2,6,4,4,2,4,3,5,5,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [40]:
# list columns with null values and its count
print(df.isnull().sum()[df.isnull().sum() > 0])

Street Address    1682
Barangay            70
dtype: int64

In [41]:
# fill them with 'Not Provided'
df.fillna({'Street Address': 'Not Provided'}, inplace=True)
df.fillna({'Barangay': 'Not Provided'}, inplace=True)

In [42]:
# recheck columns with null values and its count
print(df.isnull().sum()[df.isnull().sum() > 0])

Series([], dtype: int64)

In [43]:
# check dtypes
for col in df.columns:
    print(f"{col}: {df[col].dtype}")

Region: object
Division: object
District: object
BEIS School ID: int64
School Name: object
Street Address: object
Province: object
Municipality: object
Legislative District: object
Barangay: object
Sector: object
School Subclassification: object
School Type: object
Modified COC: object
K Male: int64
K Female: int64
G1 Male: int64
G1 Female: int64
G2 Male: int64
G2 Female: int64
G3 Male: int64
G3 Female: int64
G4 Male: int64
G4 Female: int64
G5 Male: int64
G5 Female: int64
G6 Male: int64
G6 Female: int64
Elem NG Male: int64
Elem NG Female: int64
G7 Male: int64
G7 Female: int64
G8 Male: int64
G8 Female: int64
G9 Male: int64
G9 Female: int64
G10 Male: int64
G10 Female: int64
JHS NG Male: int64
JHS NG Female: int64
G11 ACAD - ABM Male: int64
G11 ACAD - ABM Female: int64
G11 ACAD - HUMSS Male: int64
G11 ACAD - HUMSS Female: int64
G11 ACAD STEM Male: int64
G11 ACAD STEM Female: int64
G11 ACAD GAS Male: int64
G11 ACAD GAS Female: int64
G11 ACAD PBM Male: int64
G11 ACAD PBM Female: int64
G11 TVL Male: int64
G11 TVL Female: int64
G11 SPORTS Male: int64
G11 SPORTS Female: int64
G11 ARTS Male: int64
G11 ARTS Female: int64
G12 ACAD - ABM Male: int64
G12 ACAD - ABM Female: int64
G12 ACAD - HUMSS Male: int64
G12 ACAD - HUMSS Female: int64
G12 ACAD STEM Male: int64
G12 ACAD STEM Female: int64
G12 ACAD GAS Male: int64
G12 ACAD GAS Female: int64
G12 ACAD PBM Male: int64
G12 ACAD PBM Female: int64
G12 TVL Male: int64
G12 TVL Female: int64
G12 SPORTS Male: int64
G12 SPORTS Female: int64
G12 ARTS Male: int64
G12 ARTS Female: int64

In [44]:
# check for duplicates
duplicate_school_ids = df[df.duplicated(subset=['BEIS School ID'])]
print(f"Total Duplicate School IDs: {duplicate_school_ids.shape[0]}")

Total Duplicate School IDs: 0

In [45]:
# Define a list of invalid values (including "None" as a string)
invalid_values = ["N/A", "", " ", "NULL", "NaN", "-", "###", "@@!!", "None"]

# Count invalid entries in each column
invalid_counts = df.isin(invalid_values).sum()

# Filter only columns with invalid entries
invalid_counts = invalid_counts[invalid_counts > 0]

# Display the result
print("Invalid Entries Per Column:\n", invalid_counts)

Invalid Entries Per Column:
 Street Address    2375
dtype: int64

In [46]:
# since there are lots of invalid street address, it is better to just drop it since will not affect the enrollment dashboard by doing so
df.drop(columns=['Street Address'], inplace=True)

In [47]:
df

,Region,Division,District,BEIS School ID,School Name,Province,Municipality,Legislative District,Barangay,Sector,School Subclassification,School Type,Modified COC,K Male,K Female,G1 Male,G1 Female,G2 Male,G2 Female,G3 Male,G3 Female,G4 Male,G4 Female,G5 Male,G5 Female,G6 Male,G6 Female,Elem NG Male,Elem NG Female,G7 Male,G7 Female,G8 Male,G8 Female,G9 Male,G9 Female,G10 Male,G10 Female,JHS NG Male,JHS NG Female,G11 ACAD - ABM Male,G11 ACAD - ABM Female,G11 ACAD - HUMSS Male,G11 ACAD - HUMSS Female,G11 ACAD STEM Male,G11 ACAD STEM Female,G11 ACAD GAS Male,G11 ACAD GAS Female,G11 ACAD PBM Male,G11 ACAD PBM Female,G11 TVL Male,G11 TVL Female,G11 SPORTS Male,G11 SPORTS Female,G11 ARTS Male,G11 ARTS Female,G12 ACAD - ABM Male,G12 ACAD - ABM Female,G12 ACAD - HUMSS Male,G12 ACAD - HUMSS Female,G12 ACAD STEM Male,G12 ACAD STEM Female,G12 ACAD GAS Male,G12 ACAD GAS Female,G12 ACAD PBM Male,G12 ACAD PBM Female,G12 TVL Male,G12 TVL Female,G12 SPORTS Male,G12 SPORTS Female,G12 ARTS Male,G12 ARTS Female
0,Region I,Ilocos Norte,Bacarra I,100001,Apaleng-Libtong ES,ILOCOS NORTE,BACARRA,1st District,LIBTONG,Public,DepED Managed,School with no Annexes,Purely ES,4,5,3,2,5,7,5,1,2,2,2,9,2,9,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,Region I,Ilocos Norte,Bacarra I,100002,Bacarra CES,ILOCOS NORTE,BACARRA,1st District,SANTA RITA (POB.),Public,DepED Managed,School with no Annexes,Purely ES,26,25,33,25,18,29,23,32,30,23,34,35,27,42,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,Region I,Ilocos Norte,Bacarra I,100003,Buyon ES,ILOCOS NORTE,BACARRA,1st District,BUYON,Public,DepED Managed,School with no Annexes,Purely ES,8,10,11,10,11,4,13,4,8,7,12,14,9,7,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,Region I,Ilocos Norte,Bacarra I,100004,Ganagan Elementary School,ILOCOS NORTE,BACARRA,1st District,GANAGAN,Public,DepED Managed,School with no Annexes,Purely ES,9,8,5,4,6,5,6,8,7,5,1,13,7,7,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,Region I,Ilocos Norte,Bacarra I,100005,Macupit ES,ILOCOS NORTE,BACARRA,1st District,MACUPIT,Public,DepED Managed,School with no Annexes,Purely ES,5,3,5,2,3,2,6,4,4,2,4,3,5,5,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60162,PSO,Italy,Lazio,700034,International Philippine School in Italy,NCR SECOND DISTRICT,CITY OF PASIG,Lone District,Not Provided,PSO,SCHOOL ABROAD,School with no Annexes,ES and JHS,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
60163,PSO,Sultanate of Oman,Muscat,700026,Philippine School,NCR SECOND DISTRICT,CITY OF PASIG,Lone District,Not Provided,PSO,SCHOOL ABROAD,School with no Annexes,All Offering,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,12,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
60164,PSO,State of Kuwait,Jleeb Al-Shuyoukh,700027,The New Kuwait-Philippines International School,NCR SECOND DISTRICT,CITY OF PASIG,Lone District,Not Provided,PSO,SCHOOL ABROAD,School with no Annexes,All Offering,24,27,19,10,15,13,14,18,23,13,14,17,19,26,0,0,11,23,20,11,24,17,17,17,0,0,2,7,0,0,5,4,0,0,0,0,0,0,0,0,0,0,4,3,0,0,5,1,0,0,0,0,0,0,0,0,0,0
60165,PSO,State of Kuwait,Fahaheel,700030,Philippine International English School,NCR SECOND DISTRICT,CITY OF PASIG,Lone District,Not Provided,PSO,SCHOOL ABROAD,School with no Annexes,All Offering,0,0,18,25,27,19,24,21,13,0,0,0,22,26,0,0,16,23,21,20,31,21,26,30,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,8,6,1,0,0,0,0,0,0,0,0,0
60166,PSO,Greece,Athens,700031,Philippine School in Greece,NCR SECOND DISTRICT,CITY OF PASIG,Lone District,Not Provided,PSO,SCHOOL ABROAD,School with no Annexes,ES and JHS,1,1,1,3,2,2,3,4,4,3,4,0,6,3,0,0,7,7,8,2,9,10,5,13,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [48]:
# create a function for school name normalization

import re
import pandas as pd

# abbreviation replacements
abbrvs = {
    r'\b(E/S|ES|E.S.|ELEM.)\b': 'ELEMENTARY',
    r'\b(NHS)\b': 'NATIONAL HIGH SCHOOL',
    r'\b(SHS)\b': 'SENIOR HIGH SCHOOL',
    r'\b(CES)\b': 'CENTRAL ELEMENTARY SCHOOL',
    r'\b(MES)\b': 'MUNICIPAL ELEMENTARY SCHOOL',
    r'\b(CS)\b': 'CENTRAL SCHOOL',
    r'\b(PS|P/S)\b': 'PRIMARY SCHOOL',
    r'\b(HS|H.S.)\b': 'HIGH SCHOOL',
    r'\b(IS)\b': 'INTEGRATED SCHOOL',
    r'\b(IP)\b': 'INDIGENOUS PEOPLES',
    r'\b(MS|MEM.|MEMO.)\b': 'MEMORIAL',
    r'\b(MNHS)\b': 'MEMORIAL NATIONAL HIGH SCHOOL',
    r'\b(NCHS)\b': 'NATIONAL COMPREHENSIVE HIGH SCHOOL',
    r'\b(CNHS)\b': 'COMPREHENSIVE NATIONAL HIGH SCHOOL',
    r'\b(SOF)\b': 'SCHOOL OF FISHERIES',
    r'\b(SCH.|SCHOOL.)\b': 'SCHOOL',
    r'\b(COM.|COMM.)\b': 'COMMUNITY',   
    r'\bBO.\b': 'BARRIO',              
    r'\b(INC|INCORPORATED|INCORPORATION)\b': ', INC.'
}



def fix_parentheses_and_uppercase(name):
    if pd.isna(name):
        return name
    
    # replace abbrvs
    for pattern, replacement in abbrvs.items():
        name = re.sub(pattern, replacement, name, flags=re.IGNORECASE)
    
    # fix missing parentheses
    open_count, close_count = name.count('('), name.count(')')
    if open_count > close_count:
        name += ')'
    elif close_count > open_count:
        name = '(' + name

    # ensure proper spacing around dashes
    name = re.sub(r'\s*-\s*', ' - ', name)  # Ensures a single space around '-'
    name = re.sub(r',\s*', ', ', name)  # Ensures a single space after commas

    # convert everything to uppercase
    name = name.upper()
    
    # remove unnecessary spaces before commas
    name = re.sub(r'\s+,', ',', name)  # Removes spaces before commas

    # remove unnecessary characters
    name = name.replace('"', '').replace("'", '')
    name = re.sub(r',,+', ',', name)  # fix double commas
    name = re.sub(r'\.+', '.', name)  # fix double periods
    name = re.sub(r'\(\s+', '(', name)  # removes space after open parenthesis
    name = re.sub(r'\s+\)', ')', name)  # removes space before closing parenthesis
    name = re.sub(r'\s+', ' ', name).strip()  # remove extra spaces
    
    return name

# apply transformations to the DataFrame
df['School Name'] = df['School Name'].apply(fix_parentheses_and_uppercase)

In [49]:
# replace 'SCHOOL.' with 'SCHOOL' in all values
df = df.map(lambda x: x.replace("SCHOOL.", "SCHOOL") if isinstance(x, str) else x)

# additional cleanup
manual_correction = {
    '(4TH WATCH) MARANATHA CHRISTIAN SCHOOLOF LAPU - LAPU CITY, INC.':'4TH WATCH MARANATHA CHRISTIAN SCHOOLOF LAPU - LAPU CITY, INC.',
    '(4TH WATCH)MARANATHA CHRISTIAN SCHOOLOF TALISAY CITY, CEBU, INC.':'4TH WATCH MARANATHA CHRISTIAN SCHOOLOF TALISAY CITY, CEBU, INC.',
    '(COMPOSTELA NATIONAL HIGH SCHOOLDAY CLASS)':'COMPOSTELA NATIONAL HIGH SCHOOLDAY CLASS',
    '(FTJCA) FAMILY TABERNACLE OF JESUS CHRIST ALMIGHTY CHRISTIAN ACADEMY':'FAMILY TABERNACLE OF JESUS CHRIST ALMIGHTY CHRISTIAN ACADEMY',
    '(HIS) HOPE INTEGRATED SCHOOL, INC.':'HOPE INTEGRATED SCHOOL, INC.',
    '(FELIPE P. PANTON HIGH SCHOOLFORMERLY:INOYONAN NATIONAL HIGH SCHOOL)':'FELIPE P. PANTON HIGH SCHOOLFORMERLY:INOYONAN NATIONAL HIGH SCHOOL',
    '(ESMERALDO ROQUE MUNICIPAL ELEMENTARY SCHOOLMUNTAY)':'ESMERALDO ROQUE MUNICIPAL ELEMENTARY SCHOOLMUNTAY',
    '(LURAY II NATIONAL HIGH SCHOOL (DAY & NIGHT))':'LURAY II NATIONAL HIGH SCHOOL (DAY & NIGHT)',
    '(PICONG NATIONAL HIGH SCHOOLRA 9575)': 'PICONG NATIONAL HIGH SCHOOLRA 9575',
    '(POONAPIAGAPO NATIONAL HIGH SCHOOLANNEX MATUNGAO NATIONAL HIGH SCHOOL)':'POONAPIAGAPO NATIONAL HIGH SCHOOLANNEX MATUNGAO NATIONAL HIGH SCHOOL',
    '(S.J.B.) SAINT JOHN BOSCO, I.A.S., INC.':'SAINT JOHN BOSCO, I.A.S., INC.',
    '(ST. ANTHONY DE PADUA LEARNING SCHOOLBATASAN), INC.':'ST. ANTHONY DE PADUA LEARNING SCHOOLBATASAN, INC.',
    '(SULTAN ANGIN MEM. NATIONAL HIGH SCHOOLFORMERLY SAGUIARAN NATIONAL HIGH SCHOOL)':'SULTAN ANGIN MEM. NATIONAL HIGH SCHOOLFORMERLY SAGUIARAN NATIONAL HIGH SCHOOL',
    '(WENDELIN EDUARTE ELEMENTARY SCHOOLGUMAGA ELEMENTARY)':'WENDELIN EDUARTE ELEMENTARY SCHOOLGUMAGA ELEMENTARY',
    'BONGAO CLES':'BONGAO Central Elementary School'
}

df["School Name"] = df["School Name"].replace(manual_correction)

In [50]:
# check region column
for div in sorted(df['Region'].unique()):
    print(div)

BARMM
CAR
CARAGA
MIMAROPA
NCR
PSO
Region I
Region II
Region III
Region IV-A
Region IX
Region V
Region VI
Region VII
Region VIII
Region X
Region XI
Region XII

In [51]:
# make region names straightforward
regions = {
    'BARMM':'BANGSAMORO AUTONOMOUS REGION IN MUSLIM MINDANAO',
    'CAR':'CORDILLERA ADMINISTRATIVE REGION',
    'CARAGA':'CARAGA REGION',
    'MIMAROPA':'MIMAROPA',
    'NCR':'NATIONAL CAPITAL REGION',
    'PSO':'PHILIPPINE SCHOOLS OVERSEAS',
    'Region I':'ILOCOS REGION',
    'Region II':'CAGAYAN VALLEY',
    'Region III':'CENTRAL LUZON',
    'Region IV-A':'CALABARZON',
    'Region V':'BICOL REGION',
    'Region VI':'WESTERN VISAYAS',
    'Region VII':'CENTRAL VISAYAS',
    'Region VIII':'EASTERN VISAYAS',
    'Region IX':'ZAMBOANGA PENINSULA',
    'Region X':'NORTHERN MINDANAO',
    'Region XI':'DAVAO REGION',
    'Region XII':'SOCCSKSARGEN'
}

df['Region'] = df['Region'].map(regions)

for div in sorted(df['Region'].unique()):
    print(div)

BANGSAMORO AUTONOMOUS REGION IN MUSLIM MINDANAO
BICOL REGION
CAGAYAN VALLEY
CALABARZON
CARAGA REGION
CENTRAL LUZON
CENTRAL VISAYAS
CORDILLERA ADMINISTRATIVE REGION
DAVAO REGION
EASTERN VISAYAS
ILOCOS REGION
MIMAROPA
NATIONAL CAPITAL REGION
NORTHERN MINDANAO
PHILIPPINE SCHOOLS OVERSEAS
SOCCSKSARGEN
WESTERN VISAYAS
ZAMBOANGA PENINSULA

In [52]:
# make all division uppercase for consistency
df['Division'] = df['Division'].str.upper()

In [53]:
# simplify disctrict name
no_district = {
    '(No District) - For SGA Division':'NO DISTRICT'
}

df['District'] = df['District'].replace(no_district)

In [54]:
# uppercase entries
columns_to_upper = ['District', 'Municipality', 'Legislative District', 'Barangay']
df[columns_to_upper] = df[columns_to_upper].apply(lambda x: x.str.upper())

In [55]:
# check sector column
for i in sorted(df['Sector'].unique()):
    print(i)

PSO
Private
Public
SUCsLUCs

In [56]:
# make sector names simpler
sectors = {
    'PSO':'PHILIPPINE SCHOOLS OVERSEAS',
    'Private':'PRIVATE',
    'Public':'PUBLIC',
    'SUCsLUCs':'STATE & LOCAL UNIVERSITIES AND COLLEGES'
}

df['Sector'] = df['Sector'].map(sectors)

In [57]:
# check school subclass
for i in sorted(df['School Subclassification'].unique()):
    print(i)

DOST Managed
DepED Managed
LUC
Local International School
Non-Sectarian
Other GA Managed
SCHOOL ABROAD
SUC Managed
Sectarian

In [58]:
# make sector names simpler
school_subclass = {
    'DOST Managed':'DOST MANAGED',
    'DepED Managed':'DEPED MANAGED',
    'LUC':'LOCAL UNIVERSITIES AND COLLEGES',
    'Local International School':'LOCAL INTERNATIONAL SCHOOL',
    'Non-Sectarian ':'NON-SECTARIAN',
    'Other GA Managed':'OTHER GOVERNMENT-ASSISTED MANAGED',
    'SUC Managed':'STATE UNIVERSITIES AND COLLEGES',
    'Sectarian ':'SECTARIAN'
}
df['School Subclassification'] = df['School Subclassification'].replace(school_subclass)

In [59]:
# check school type
for i in sorted(df['School Type'].unique()):
    print(i)

Annex or Extension school(s)
Mobile School(s)/Center(s)
Mother school
School with no Annexes

In [60]:
# make school type simpler
school_type = {
    'Annex or Extension school(s)':'ANNEX OR EXTENSION SCHOOL',
    'Mobile School(s)/Center(s)':'MOBILE SCHOOL OR LEARNING CENTER',
    'Mother school':'MOTHER SCHOOL',
    'School with no Annexes':'SCHOOL WITH NO ANNEXES'
}

df['School Type'] = df['School Type'].map(school_type)

In [61]:
# check modified coc
for i in sorted(df['Modified COC'].unique()):
    print(i)

All Offering
ES and JHS
JHS with SHS
Purely ES
Purely JHS
Purely SHS

In [62]:
# make it simpler
modified_coc = {
    'All Offering':'COMPLETE BASIC EDUCATION SCHOOL',
    'ES and JHS':'ELEMENTARY & JUNIOR HIGH SCHOOL',
    'JHS with SHS':'JUNIOR & SENIOR HIGH SCHOOL',
    'Purely ES':'PURELY ELEMENTARY SCHOOL',
    'Purely JHS':'PURELY JUNIOR HIGH SCHOOL',
    'Purely SHS':'PURELY SENIOR HIGH SCHOOL'
}

df['Modified COC'] = df['Modified COC'].map(modified_coc)

In [63]:
# double check null entries
print(df.isnull().sum()[df.isnull().sum() > 0])

Series([], dtype: int64)

In [64]:
# make the dataset into long format
# identify identifier columns (columns NOT related to gender)
id_vars = ['Region', 'Division', 'District', 'BEIS School ID', 'School Name', 
           'Province', 'Municipality', 'Legislative District', 'Barangay', 
           'Sector', 'School Subclassification', 'School Type', 'Modified COC']

# all other columns are gender-based, hence melt them
df_long = df.melt(id_vars=id_vars, var_name="Grade_Gender", value_name="Enrollment")

# extract "Gender" (Male/Female)
df_long["Gender"] = df_long["Grade_Gender"].apply(lambda x: "Male" if "Male" in x else "Female")

# extract "Grade Level" (Remove Male/Female from column names)
df_long["Grade Level"] = df_long["Grade_Gender"].str.replace(" Male", "").str.replace(" Female", "")

# drop the original "Grade_Gender" column
df_long = df_long.drop(columns=["Grade_Gender"])

In [65]:
df_long

,Region,Division,District,BEIS School ID,School Name,Province,Municipality,Legislative District,Barangay,Sector,School Subclassification,School Type,Modified COC,Enrollment,Gender,Grade Level
0,ILOCOS REGION,ILOCOS NORTE,BACARRA I,100001,APALENG - LIBTONG ELEMENTARY,ILOCOS NORTE,BACARRA,1ST DISTRICT,LIBTONG,PUBLIC,DEPED MANAGED,SCHOOL WITH NO ANNEXES,PURELY ELEMENTARY SCHOOL,4,Male,K
1,ILOCOS REGION,ILOCOS NORTE,BACARRA I,100002,BACARRA CENTRAL ELEMENTARY SCHOOL,ILOCOS NORTE,BACARRA,1ST DISTRICT,SANTA RITA (POB.),PUBLIC,DEPED MANAGED,SCHOOL WITH NO ANNEXES,PURELY ELEMENTARY SCHOOL,26,Male,K
2,ILOCOS REGION,ILOCOS NORTE,BACARRA I,100003,BUYON ELEMENTARY,ILOCOS NORTE,BACARRA,1ST DISTRICT,BUYON,PUBLIC,DEPED MANAGED,SCHOOL WITH NO ANNEXES,PURELY ELEMENTARY SCHOOL,8,Male,K
3,ILOCOS REGION,ILOCOS NORTE,BACARRA I,100004,GANAGAN ELEMENTARY SCHOOL,ILOCOS NORTE,BACARRA,1ST DISTRICT,GANAGAN,PUBLIC,DEPED MANAGED,SCHOOL WITH NO ANNEXES,PURELY ELEMENTARY SCHOOL,9,Male,K
4,ILOCOS REGION,ILOCOS NORTE,BACARRA I,100005,MACUPIT ELEMENTARY,ILOCOS NORTE,BACARRA,1ST DISTRICT,MACUPIT,PUBLIC,DEPED MANAGED,SCHOOL WITH NO ANNEXES,PURELY ELEMENTARY SCHOOL,5,Male,K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3489681,PHILIPPINE SCHOOLS OVERSEAS,ITALY,LAZIO,700034,INTERNATIONAL PHILIPPINE SCHOOLIN ITALY,NCR SECOND DISTRICT,CITY OF PASIG,LONE DISTRICT,NOT PROVIDED,PHILIPPINE SCHOOLS OVERSEAS,SCHOOL ABROAD,SCHOOL WITH NO ANNEXES,ELEMENTARY & JUNIOR HIGH SCHOOL,0,Female,G12 ARTS
3489682,PHILIPPINE SCHOOLS OVERSEAS,SULTANATE OF OMAN,MUSCAT,700026,PHILIPPINE SCHOOL,NCR SECOND DISTRICT,CITY OF PASIG,LONE DISTRICT,NOT PROVIDED,PHILIPPINE SCHOOLS OVERSEAS,SCHOOL ABROAD,SCHOOL WITH NO ANNEXES,COMPLETE BASIC EDUCATION SCHOOL,0,Female,G12 ARTS
3489683,PHILIPPINE SCHOOLS OVERSEAS,STATE OF KUWAIT,JLEEB AL-SHUYOUKH,700027,THE NEW KUWAIT - PHILIPPINES INTERNATIONAL SCHOOL,NCR SECOND DISTRICT,CITY OF PASIG,LONE DISTRICT,NOT PROVIDED,PHILIPPINE SCHOOLS OVERSEAS,SCHOOL ABROAD,SCHOOL WITH NO ANNEXES,COMPLETE BASIC EDUCATION SCHOOL,0,Female,G12 ARTS
3489684,PHILIPPINE SCHOOLS OVERSEAS,STATE OF KUWAIT,FAHAHEEL,700030,PHILIPPINE INTERNATIONAL ENGLISH SCHOOL,NCR SECOND DISTRICT,CITY OF PASIG,LONE DISTRICT,NOT PROVIDED,PHILIPPINE SCHOOLS OVERSEAS,SCHOOL ABROAD,SCHOOL WITH NO ANNEXES,COMPLETE BASIC EDUCATION SCHOOL,0,Female,G12 ARTS
3489685,PHILIPPINE SCHOOLS OVERSEAS,GREECE,ATHENS,700031,PHILIPPINE SCHOOLIN GREECE,NCR SECOND DISTRICT,CITY OF PASIG,LONE DISTRICT,NOT PROVIDED,PHILIPPINE SCHOOLS OVERSEAS,SCHOOL ABROAD,SCHOOL WITH NO ANNEXES,ELEMENTARY & JUNIOR HIGH SCHOOL,0,Female,G12 ARTS

In [66]:
# double check new column
for i in sorted(df_long['Grade Level'].unique()):
    print(i)

Elem NG
G1
G10
G11 ACAD - ABM
G11 ACAD - HUMSS
G11 ACAD GAS
G11 ACAD PBM
G11 ACAD STEM
G11 ARTS
G11 SPORTS
G11 TVL
G12 ACAD - ABM
G12 ACAD - HUMSS
G12 ACAD GAS
G12 ACAD PBM
G12 ACAD STEM
G12 ARTS
G12 SPORTS
G12 TVL
G2
G3
G4
G5
G6
G7
G8
G9
JHS NG
K

In [67]:
# normalize unique values
grade_level = {
    'K':'KINDER',
    'Elem NG':'ELEM NON-GRADED',
    'JHS NG':'JHS NON-GRADED',
    'G1':'1',
    'G2':'2',
    'G3':'3',
    'G4':'4',
    'G5':'5',
    'G6':'6',
    'G7':'7',
    'G8':'8',
    'G9':'9',
    'G10':'10',
    'G11 ACAD - ABM':'11-ABM',
    'G11 ACAD - HUMSS':'11-HUMSS',
    'G11 ACAD GAS':'11-GAS',
    'G11 ACAD PBM':'11-PBM',
    'G11 ACAD STEM':'11-STEM',

    'G11 ARTS':'11-ARTS',
    'G11 SPORTS':'11-SPORTS',
    'G11 TVL':'11-TVL',

    'G12 ACAD - ABM':'12-ABM',
    'G12 ACAD - HUMSS':'12-HUMSS',
    'G12 ACAD GAS':'12-GAS',
    'G12 ACAD PBM':'12-PBM',
    'G12 ACAD STEM':'12-STEM',

    'G12 ARTS':'12-ARTS',
    'G12 SPORTS':'12-SPORTS',
    'G12 TVL':'12-TVL',
}
df_long['Grade Level'] = df_long['Grade Level'].replace(grade_level)

In [68]:
# check new column
for i in sorted(df_long['Grade Level'].unique()):
    print(i)

1
10
11-ABM
11-ARTS
11-GAS
11-HUMSS
11-PBM
11-SPORTS
11-STEM
11-TVL
12-ABM
12-ARTS
12-GAS
12-HUMSS
12-PBM
12-SPORTS
12-STEM
12-TVL
2
3
4
5
6
7
8
9
ELEM NON-GRADED
JHS NON-GRADED
KINDER

In [69]:
# check new column
for i in sorted(df_long['Gender'].unique()):
    print(i)

Female
Male

In [70]:
# checking final dataset
df_long

,Region,Division,District,BEIS School ID,School Name,Province,Municipality,Legislative District,Barangay,Sector,School Subclassification,School Type,Modified COC,Enrollment,Gender,Grade Level
0,ILOCOS REGION,ILOCOS NORTE,BACARRA I,100001,APALENG - LIBTONG ELEMENTARY,ILOCOS NORTE,BACARRA,1ST DISTRICT,LIBTONG,PUBLIC,DEPED MANAGED,SCHOOL WITH NO ANNEXES,PURELY ELEMENTARY SCHOOL,4,Male,KINDER
1,ILOCOS REGION,ILOCOS NORTE,BACARRA I,100002,BACARRA CENTRAL ELEMENTARY SCHOOL,ILOCOS NORTE,BACARRA,1ST DISTRICT,SANTA RITA (POB.),PUBLIC,DEPED MANAGED,SCHOOL WITH NO ANNEXES,PURELY ELEMENTARY SCHOOL,26,Male,KINDER
2,ILOCOS REGION,ILOCOS NORTE,BACARRA I,100003,BUYON ELEMENTARY,ILOCOS NORTE,BACARRA,1ST DISTRICT,BUYON,PUBLIC,DEPED MANAGED,SCHOOL WITH NO ANNEXES,PURELY ELEMENTARY SCHOOL,8,Male,KINDER
3,ILOCOS REGION,ILOCOS NORTE,BACARRA I,100004,GANAGAN ELEMENTARY SCHOOL,ILOCOS NORTE,BACARRA,1ST DISTRICT,GANAGAN,PUBLIC,DEPED MANAGED,SCHOOL WITH NO ANNEXES,PURELY ELEMENTARY SCHOOL,9,Male,KINDER
4,ILOCOS REGION,ILOCOS NORTE,BACARRA I,100005,MACUPIT ELEMENTARY,ILOCOS NORTE,BACARRA,1ST DISTRICT,MACUPIT,PUBLIC,DEPED MANAGED,SCHOOL WITH NO ANNEXES,PURELY ELEMENTARY SCHOOL,5,Male,KINDER
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3489681,PHILIPPINE SCHOOLS OVERSEAS,ITALY,LAZIO,700034,INTERNATIONAL PHILIPPINE SCHOOLIN ITALY,NCR SECOND DISTRICT,CITY OF PASIG,LONE DISTRICT,NOT PROVIDED,PHILIPPINE SCHOOLS OVERSEAS,SCHOOL ABROAD,SCHOOL WITH NO ANNEXES,ELEMENTARY & JUNIOR HIGH SCHOOL,0,Female,12-ARTS
3489682,PHILIPPINE SCHOOLS OVERSEAS,SULTANATE OF OMAN,MUSCAT,700026,PHILIPPINE SCHOOL,NCR SECOND DISTRICT,CITY OF PASIG,LONE DISTRICT,NOT PROVIDED,PHILIPPINE SCHOOLS OVERSEAS,SCHOOL ABROAD,SCHOOL WITH NO ANNEXES,COMPLETE BASIC EDUCATION SCHOOL,0,Female,12-ARTS
3489683,PHILIPPINE SCHOOLS OVERSEAS,STATE OF KUWAIT,JLEEB AL-SHUYOUKH,700027,THE NEW KUWAIT - PHILIPPINES INTERNATIONAL SCHOOL,NCR SECOND DISTRICT,CITY OF PASIG,LONE DISTRICT,NOT PROVIDED,PHILIPPINE SCHOOLS OVERSEAS,SCHOOL ABROAD,SCHOOL WITH NO ANNEXES,COMPLETE BASIC EDUCATION SCHOOL,0,Female,12-ARTS
3489684,PHILIPPINE SCHOOLS OVERSEAS,STATE OF KUWAIT,FAHAHEEL,700030,PHILIPPINE INTERNATIONAL ENGLISH SCHOOL,NCR SECOND DISTRICT,CITY OF PASIG,LONE DISTRICT,NOT PROVIDED,PHILIPPINE SCHOOLS OVERSEAS,SCHOOL ABROAD,SCHOOL WITH NO ANNEXES,COMPLETE BASIC EDUCATION SCHOOL,0,Female,12-ARTS
3489685,PHILIPPINE SCHOOLS OVERSEAS,GREECE,ATHENS,700031,PHILIPPINE SCHOOLIN GREECE,NCR SECOND DISTRICT,CITY OF PASIG,LONE DISTRICT,NOT PROVIDED,PHILIPPINE SCHOOLS OVERSEAS,SCHOOL ABROAD,SCHOOL WITH NO ANNEXES,ELEMENTARY & JUNIOR HIGH SCHOOL,0,Female,12-ARTS

In [71]:
# exporting the dataset and ensure that special characters are properly saved
# df_long.to_csv('data_for_dashboarding.csv', encoding='utf-8-sig', index=False)